import {Store} from './store';

export const MemoryExpress: Store = {
  currency: '$',
  labels: {
    maxPrice: {
      container:
        '#ProductPricing .GrandTotal.c-capr-pricing__grand-total > div',
      euroFormat: false,
    },
    outOfStock: {
      // container:
      //   '.c-capr-inventory-selector__details-online .c-capr-inventory-store__availability',
      // text: ['Out of Stock', 'Backorder'],
      // TODO: Add 1660 [ti/super], 6600, 6600xt,
      container:
        'li[data-region-name="Ontario"] .c-capr-inventory-store__availability',
      text: ['Out of Stock'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.memoryexpress.com/Products/MX79473',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00118951',
    },
    {
      brand: 'xfx',
      model: 'swft',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00118728',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00119071',
    },
    {
      brand: 'xfx',
      model: 'swft',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00119327',
    },
    {
      brand: 'xfx',
      model: 'qick',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118032',
    },
    {
      brand: 'msi',
      model: 'mech 2x',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118191',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118338',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118337',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79540',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX00118866',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX00118882',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00120009',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00116283',
    },
    {
      brand: 'zotac',
      model: 'gaming',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX00120679',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79541',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX00120779',
    },
    {
      brand: 'asus',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79618',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116071',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116072',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116164',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116013',
    },
    {
      brand: 'gigabyte',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79427',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117403',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117401',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117402',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00120105',
    },
    {
      brand: 'asus',
      model: 'phoenix',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118346',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117931',
    },
    {
      brand: 'zotac',
      model: 'gaming',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00120677',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117683',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117400',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00122319',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118241',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118342',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118028',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117682',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118025',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118027',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00120705',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118491',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118344',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118376',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117884',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118387',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118517',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118107',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117680',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118377',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117681',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118378',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118390',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00122866',
    },
    {
      brand: 'msi',
      model: 'gaming z trio',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117679',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118375',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00121109',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00114408',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118392',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117676',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00119893',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117404',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117552',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118490',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00114447',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117587',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117442',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117460',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117441',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00119306',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118385',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117586',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117413',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118618',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00120566',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00117777',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118380',
    },
    {
      brand: 'msi',
      model: 'gaming z trio',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00120251',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00122538',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118345',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118106',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117393',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00120375',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118518',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114093',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00115133',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114001',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123314',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123396',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00113952',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117382',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123313',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00122044',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123265',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123382',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123381',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00121317',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117359',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123398',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123379',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '4080',
      url: 'https://www.memoryexpress.com/Products/MX00123399',
    },
    {
      brand: 'gigabyte',
      model: 'windforce',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122932',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00123009',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122975',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122931',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122973',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122930',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00123008',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00122929',
    },
    {
      brand: 'asus',
      model: 'oc',
      series: '4090',
      url: 'https://www.memoryexpress.com/Products/MX00123007',
    },
  ],
  name: 'memoryexpress',
  waitUntil: 'domcontentloaded',
};
