import {Store} from './store';

export const MemoryExpress: Store = {
  currency: '$',
  labels: {
    maxPrice: {
      container:
        '#ProductPricing .GrandTotal.c-capr-pricing__grand-total > div',
      euroFormat: false,
    },
    outOfStock: {
      container:
        '.c-capr-inventory-selector__details-online .c-capr-inventory-store__availability',
      text: ['Out of Stock', 'Backorder'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.memoryexpress.com/Products/MX79473',
    },
    {
      brand: 'xfx',
      model: 'swft',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00118728',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00118951',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00119071',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118338',
    },
    {
      brand: 'msi',
      model: 'mech 2x',
      series: 'rx6600',
      url: 'https://www.memoryexpress.com/Products/MX00118890',
    },
    {
      brand: 'sapphire',
      model: 'pulse',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118225',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118337',
    },
    {
      brand: 'msi',
      model: 'mech 2x',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118191',
    },
    {
      brand: 'sapphire',
      model: 'nitro+',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118224',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118335',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118190',
    },
    {
      brand: 'asus',
      model: 'gaming',
      series: 'rx6600xt',
      url: 'https://www.memoryexpress.com/Products/MX00118513',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX00115110',
    },
    {
      brand: 'gigabyte',
      model: 'oc',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX76273',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX00115109',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX77285',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79474',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX76363',
    },
    {
      brand: 'asus',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79618',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX00112766',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79616',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79569',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX76272',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX77286',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '1660',
      url: 'https://www.memoryexpress.com/Products/MX76270',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX75788',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX80379',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX75926',
    },
    {
      brand: 'gigabyte',
      model: 'oc',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX75801',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX75792',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79473',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '1660ti',
      url: 'https://www.memoryexpress.com/Products/MX75828',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79540',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00116283',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '2060',
      url: 'https://www.memoryexpress.com/Products/MX00117136',
    },
    {
      brand: 'asus',
      model: 'phoenix',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118346',
    },
    {
      brand: 'gigabyte',
      model: 'oc',
      series: '1660super',
      url: 'https://www.memoryexpress.com/Products/MX79427',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116013',
    },
    {
      brand: 'asus',
      model: 'phoenix',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117476',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117931',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118491',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117403',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116063',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116071',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116072',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117588',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00118344',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116154',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116164',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117402',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117401',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00116163',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3060',
      url: 'https://www.memoryexpress.com/Products/MX00117400',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00115013',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118026',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118342',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117683',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00114926',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118107',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117884',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118028',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117682',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00114925',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117776',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118390',
    },
    {
      brand: 'zotac',
      model: 'gaming',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00117698',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118025',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00114924',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118392',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117681',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117680',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00118027',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118387',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00114566',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118376',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3060ti',
      url: 'https://www.memoryexpress.com/Products/MX00114923',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118377',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118517',
    },
    {
      brand: 'msi',
      model: 'gaming z trio',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117679',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117587',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118378',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118385',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00117676',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117442',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070',
      url: 'https://www.memoryexpress.com/Products/MX00118375',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117441',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117552',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117404',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117586',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117798',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117460',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118106',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118036',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118518',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118618',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118542',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118380',
    },
    {
      brand: 'zotac',
      model: 'gaming',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118130',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00117777',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3070ti',
      url: 'https://www.memoryexpress.com/Products/MX00117413',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118345',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118341',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00119055',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3080',
      url: 'https://www.memoryexpress.com/Products/MX00118076',
    },
    {
      brand: 'evga',
      model: 'gaming',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117360',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00118004',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117826',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117359',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117382',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117381',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117362',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00118030',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117393',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117573',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114686',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3080ti',
      url: 'https://www.memoryexpress.com/Products/MX00117391',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114001',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00113953',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114093',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114155',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00113952',
    },
    {
      brand: 'msi',
      model: 'oc',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00113958',
    },
    {
      brand: 'gigabyte',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114685',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00113959',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00115133',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114401',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114908',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00114397',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00115661',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3090',
      url: 'https://www.memoryexpress.com/Products/MX00115663',
    },
    {
      brand: 'pny',
      model: 'qick ultra',
      series: 'a4000',
      url: 'https://www.memoryexpress.com/Products/MX00118395',
    },
  ],
  name: 'memoryexpress',
  waitUntil: 'domcontentloaded',
};
